site: LING 270
url: https://2021-fall-uiuc-ling270.github.io/
title: LING 270
description: Language, Technology, and Society

permalink: pretty

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap  

  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
